# Default values for Ombi.

image:
  repository: linuxserver/ombi
  pullPolicy: Always
  tag: latest

strategy:
  type: Recreate

service:
  port:
    port: 3579

env: {}
  # TZ: UTC
  # PUID: 1001
  # PGID: 1001

persistence:
  config:
    enabled: false
    emptyDir: false

# Enabled mariadb
# ... for more options see https://github.com/bitnami/charts/tree/master/bitnami/mariadb
mariadb:
  enabled: false
  architecture: standalone
  auth:
    database: ombi
    username: ombi
    password: ombi
    rootPassword: ombi
  primary:
    persistence:
      enabled: false
