apiVersion: apps/v1
kind: Deployment
metadata:
  name: emby
  labels:
    app: emby
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emby
  template:
    metadata:
      labels:
        app: emby
    spec:
      nodeSelector:
        kubernetes.io/hostname: magnet
      containers:
        - name: emby
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8096
            - containerPort: 8920
          env:
            - name: UID
              value: "1001"
            - name: GID
              value: "1001"
          volumeMounts:
            - name: emby-storage
              mountPath: /config
              subPath: emby
            - mountPath: "/mnt/glusterfs"
              name: glusterfs-media
            - mountPath: /tmp/emby
              name: transcode
          resources:
            limits:
              gpu.intel.com/i915: 1
          securityContext:
            runAsUser: 0
      volumes:
        - name: emby-storage
          persistentVolumeClaim:
            claimName: shared-data
        - name: glusterfs-media
          glusterfs:
            endpoints: glusterfs-cluster
            path: /gmedia
        - name: transcode
          hostPath:
            path: /tmp/emby
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: emby
  annotations:
    metallb.universe.tf/allow-shared-ip: onion
spec:
  ports:
    - name: http
      port: 8096
  selector:
    app: emby
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.10.105