apiVersion: v1
kind: Service
metadata:
  name: whoami-service
  namespace: default
  annotations: traefik.ingress.kubernetes.io/service.sticky: "true"
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
