apiVersion: v1
kind: ConfigMap
metadata:
  name: transmission-config
  # namespace: transmission
data:
  LOCAL_NETWORK: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
  OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60
  OPENVPN_PROVIDER: NORDVPN
  NORDVPN_COUNTRY: DE
  NORDVPN_CATEGORY: "legacy_standard"
  NORDVPN_PROTOCOL: tcp
  TRANSMISSION_DOWNLOAD_QUEUE_SIZE: "25"
  TRANSMISSION_RATIO_LIMIT: "0"
  TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
  TRANSMISSION_SPEED_LIMIT_DOWN: "34000"
  TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED: "true"
  TRANSMISSION_SPEED_LIMIT_UP: "10"
  TRANSMISSION_SPEED_LIMIT_UP_ENABLED: "true"
  WEBPROXY_ENABLED: "true"
  WEBPROXY_PORT: "8888"
  TZ: UTC
  PUID: "1001"
  PGID: "1001"