apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: transmission
spec:
  rules:
  - host: transmission.domain.tld
    http:
      paths:
      - backend:
          serviceName: transmission
          servicePort: 9091