apiVersion: v1
kind: Service
metadata:
  name: transmission
  # namespace: transmission
spec:
  selector:
    app:  transmission
  ports:
  - name: web
    port: 9091
    protocol: TCP
    targetPort: 9091
  - name: proxy
    port: 8888
    protocol: TCP
    targetPort: 8888
  sessionAffinity: None
  type: ClusterIP