apiVersion: v1
kind: Service
metadata:
  name: transmission-local
  annotations:
    metallb.universe.tf/allow-shared-ip: onion
spec:
  selector:
    app:  transmission
  sessionAffinity: None
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.10.105
  ports:
  - port: 8888
    name: proxy
    protocol: TCP
    targetPort: 8888
  - port: 9091
    name: trans
    protocol: TCP
    targetPort: 9091