apiVersion: v1
kind: Service
metadata:
  name: transmission-local
  # namespace: transmission
spec:
  selector:
    app:  transmission
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 192.168.10.105
  ports:
  - port: 9091
    protocol: TCP
    targetPort: 9091