apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-storage-nfs
  labels:
    {{- include "storage.labels" . | nindent 4 }}
    bucket: shared
spec:
  capacity:
    storage: 450G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /media/nfs
    server: 192.168.10.3