apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data
  labels:
  {{- include "storage.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: slow
  resources:
    requests:
      storage: 450G
  selector:
    matchLabels:
      bucket: shared