apiVersion: v1
kind: Service
metadata:
  name: {{ template "filebrowser.fullname" . }}
  labels:
    app: {{ template "filebrowser.name" . }}
    chart: {{ template "filebrowser.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | trim | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port.port }}
      protocol: {{ .Values.service.port.protocol }}
      name: {{ .Values.service.port.name }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
  selector:
    app: {{ template "filebrowser.name" . }}
    release: {{ .Release.Name }}