radarr:
  image:
    repository: linuxserver/radarr
    pullPolicy: IfNotPresent
    tag: latest

  strategy:
    type: Recreate

  service:
    enabled: true
    type: LoadBalancer
    externalTrafficPolicy: Cluster
    annotations:
      metallb.universe.tf/allow-shared-ip: onion
    loadBalancerIP: 192.168.10.105
    port:
      port: 7878
      name: web
      protocol: TCP

  env:
    TZ: UTC
    PUID: 1001
    PGID: 1001

  ingress:
    enabled: false
    annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.tls: 'true'
        traefik.ingress.kubernetes.io/router.tls.certresolver: default
    labels: {}
    hosts:
      - host: radarr.vynology.com
        paths:
          - path: /
            pathType: Prefix

  persistence:
    config:
      enabled: false
      # emptyDir: false
      # existingClaim: shared-data
      # subPath: radarr
      # accessMode: ReadWriteOnce
      # size: 10Gi
      # skipuninstall: false

    media:
      enabled: false

  additionalVolumes:
  - name: config
    hostPath:
      path: /radarr
      type: DirectoryOrCreate
  - name: glusterfs-media
    glusterfs:
      endpoints: glusterfs-cluster
      path: /gmedia/video/Movies/

  additionalVolumeMounts:
    - name: config
      mountPath: /config
    - name: glusterfs-media
      mountPath: /movies

jackett:
  env:
    TZ: UTC
    PUID: 1001
    PGID: 1001

  persistence:
    config:
      enabled: false
      emptyDir: false
      existingClaim: shared-data
      subPath: jackett
      accessMode: ReadWriteOnce
      size: 1Gi
      skipuninstall: false

  torrentblackhole:
    enabled: false

  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.10.106
    ports:
    - port: 9117
      protocol: TCP
      targetPort: 9117