radarr:
  image:
    repository: linuxserver/radarr
    pullPolicy: IfNotPresent
    tag: latest

  strategy:
    type: Recreate

  service:
    enabled: true
    type: LoadBalancer
    loadBalancerIP: 192.168.10.104
    ## Specify the default port information
    port:
      port: 7878
      ## name defaults to http
      name: web
      protocol: TCP
      ## Specify a service targetPort if you wish to differ the service port from the application port.
      ## If targetPort is specified, this port number is used in the container definition instead of
      ## service.port.port. Therefore named ports are not supported for this field.
      targetPort:
      ## Specify the nodePort value for the LoadBalancer and NodePort service types.
      ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
      ##
      nodePort:

  env: {}
    # TZ: UTC
    # PUID: 1001
    # PGID: 1001

  ingress:
    enabled: false
    annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.tls: 'true'
        traefik.ingress.kubernetes.io/router.tls.certresolver: default
    labels: {}
    hosts:
      - host: radarr.vynology.com
        paths:
          - path: /
            # Ignored if not kubeVersion >= 1.14-0
            pathType: Prefix

  persistence:
    config:
      enabled: false

    media:
      enabled: false

  additionalVolumes:
  - name: config
    hostPath:
      path: /radarr
      type: DirectoryOrCreate
  - name: glusterfs-media
    glusterfs:
      endpoints: glusterfs-cluster
      path: /gmedia/video/Movies/

  additionalVolumeMounts:
    - name: config
      mountPath: /config
    - name: glusterfs-media
      mountPath: /movies
